### ISSUE TITLE
can i consume a stream if my client is behind nat

### ISSUE THREAD

**Issue by USAMAWIZARD** [vpalmisano/mediasoupbin#13]
Thanks for your reply ,
i changed local-ip to my public-ip but i  am behind a  (Router) NAT and my router is behind a career grade NAT .I am trying to consume the stream on a local PC in a network .

  File pbin.py", line 187, in on_pad_linked
    recv_rtp_socket.bind(rtp_socket_address, False)
GLib.Error: g-io-error-quark: Error binding to address: Cannot assign requested address (0)

_Originally posted by @USAMAWIZARD in https://github.com/vpalmisano/mediasoupbin/issues/10#issuecomment-1002407738_

**Comment by vpalmisano** [comment]
Not an issue that can be solved by mediasoupbin.

**Comment by USAMAWIZARD** [comment]
i changed local-ip to my public-ip but i am getting this error

File pbin.py", line 187, in on_pad_linked
recv_rtp_socket.bind(rtp_socket_address, False)
GLib.Error: g-io-error-quark: Error binding to address: Cannot assign requested address (0)
