### ISSUE TITLE
The created element should be floating, this is probably caused by faulty bindings

### ISSUE THREAD

**Issue by jmatsushita** [vpalmisano/mediasoupbin#2]
Hi there,

I'm trying to use `mediasoupbin` with gstreamer `1.17.2` and I get the following error:
```
(gst-inspect-1.0:20994): GStreamer-CRITICAL **: 13:58:34.221: The created element should be floating, this is probably caused by faulty bindings
```

Which seems to come from this check https://gitlab.freedesktop.org/gstreamer/gstreamer/blob/master/gst/gstelementfactory.c#L391

**Comment by vpalmisano** [comment]
I never seen before this error. I need more informations / code snippets.
