### ISSUE TITLE
Record using mediasoupbin

### ISSUE THREAD

**Issue by olzii** [vpalmisano/mediasoupbin#5]
How can i record my meeting using this GStreamer plugin ?

I have tried this, but it is creating 0 sized file:  ! x264enc ! mp4mux ! filesink location=/home/ugpu/video.mp4

**Comment by vpalmisano** [comment]
Are you sure that you are not receiving any data from the plugin?
Try using fakesink dumping the buffer contents.

**Comment by Alex-YddeR** [comment]
getting below error while trying with mediasoup demo

0:00:00.006574653  9251 0x5610c2297720 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "mediasoupbin_py"!
0:00:00.006705505  9251 0x5610c2297720 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "mediasoupbin_py"
0:00:00.007988499  9251 0x5610c2297720 ERROR           GST_PIPELINE grammar.y:1257:priv_gst_parse_launch: No sink-element named "(null)" - omitting link
0:00:00.008087147  9251 0x5610c2297720 ERROR           GST_PIPELINE grammar.y:1257:priv_gst_parse_launch: No sink-element named "(null)" - omitting link
WARNING: erroneous pipeline: no element "mediasoupbin_py"

**Comment by vpalmisano** [comment]
Do you have set the `GST_PLUGIN_PATH` env variable?

**Comment by Alex-YddeR** [comment]
curl -k "https://localhost:4443/rooms/test/broadcasters" | jq

From above command getting below error.
parse error: Invalid numeric literal at line 1, column 10

**Comment by vpalmisano** [comment]
You should use my branch https://github.com/vpalmisano/mediasoup-demo/tree/mediasoupbin

**Comment by Alex-YddeR** [comment]
Getting below error now when use mediasoupbin branch

/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Setting pipeline to PAUSED ...
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
Pipeline is live and does not need PREROLL ...
ERROR: from element /GstPipeline:pipeline0/mediasoupbin+MediaSoupBin:ms: 400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://vc.alex.com:4443/rooms/test/broadcasters/b42089686/transports/43d2d85c-9ed8-4c45-af3b-65d9408e7a8a/resume
Additional debug info:
400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://vc.alex.com:4443/rooms/test/broadcasters/b42089686/transports/43d2d85c-9ed8-4c45-af3b-65d9408e7a8a/resume
ERROR: pipeline doesn't want to preroll.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vc.alex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Freeing pipeline ...


Thanks
Alex

**Comment by Alex-YddeR** [comment]
root@ip-10-0-1-142:/home/ubuntu/vpalmisano/mediasoupbin#     gst-launch-1.0 mediasoupbin_py name=ms server-url="https://10.0.1.142:4443/rooms/test" local-ip=127.0.0.1 \
>     ms. ! "video/x-raw,producer-id=164e4ecf-0321-4b4c-b205-922625218f3b" ! autovideosink sync=false \
>     ms. ! "audio/x-raw,producer-id=65dd535e-8671-4985-809b-09348021a7f7" ! autoaudiosink sync=false
0:00:00.172739573 290403 0x55defabf6c40 INFO                  python mediasoupbin.py:112:do_request_new_pad: ms do_request_new_pad name_template=video_src direction=1 name=None caps=None
INFO:Signaling:__init__ serverUrl=https://10.0.1.142:4443/rooms/test broadcasterId=b47381080
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "GET /rooms/test HTTP/1.1" 200 3977
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters HTTP/1.1" 200 12
INFO:Signaling:room: {'peers': []}
0:00:00.189692950 290403 0x55defabf6c40 INFO                  python mediasoupbin.py:182:on_pad_linked: video_src on_pad_linked video/x-raw, producer-id=(string)164e4ecf-0321-4b4c-b205-922625218f3b
INFO:MediaSoup:consume {'producerId': '164e4ecf-0321-4b4c-b205-922625218f3b', 'local_ip': '127.0.0.1', 'local_rtpPort': 60351, 'local_rtcpPort': 35402}
INFO:Signaling:request createPlainRtpTransport
INFO:Signaling:do_createPlainRtpTransport {'type': 'plain', 'comedia': False, 'rtcpMux': False, 'enableSctp': False, 'appData': {}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports HTTP/1.1" 200 92
INFO:MediaSoup:consume createPlainRtpTransport {'id': '2799c353-8a01-46e7-98b7-daae1fc9d273', 'ip': '3.7.96.44', 'port': 45618, 'rtcpPort': 44137}
INFO:Signaling:request plainRtpTransportConnect
INFO:Signaling:do_plainRtpTransportConnect {'transportId': '2799c353-8a01-46e7-98b7-daae1fc9d273', 'ip': '127.0.0.1', 'port': 60351, 'rtcpPort': 35402}
INFO:Signaling:do_transportProduce {'transportId': '2799c353-8a01-46e7-98b7-daae1fc9d273', 'ip': '127.0.0.1', 'port': 60351, 'rtcpPort': 35402}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/connect HTTP/1.1" 200 0
INFO:MediaSoup:consume plainRtpTransportConnect {}
INFO:Signaling:request transportConsume
INFO:Signaling:do_transportConsume {'producerId': '164e4ecf-0321-4b4c-b205-922625218f3b', 'transportId': '2799c353-8a01-46e7-98b7-daae1fc9d273', 'paused': True, 'rtpCapabilities': {'codecs': [{'mimeType': 'audio/opus', 'clockRate': 48000, 'kind': 'audio', 'preferredPayloadType': 100, 'channels': 2, 'parameters': {'useinbandfec': 1}, 'rtcpFeedback': []}, {'mimeType': 'video/VP8', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 101, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack'}]}, {'mimeType': 'video/VP9', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 103, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack'}]}, {'mimeType': 'video/H264', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 107, 'parameters': {'packetization-mode': 1, 'profile-level-id': '42e01f', 'level-asymmetry-allowed': 1}, 'rtcpFeedback': [{'type': 'nack'}]}, {'mimeType': 'video/H265', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 109, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack'}]}]}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/consume HTTP/1.1" 200 462
INFO:MediaSoup:consume transportConsume {'id': '08e570fd-a1a0-4b77-b4c6-39e4e68ad539', 'producerId': '164e4ecf-0321-4b4c-b205-922625218f3b', 'kind': 'video', 'rtpParameters': {'codecs': [{'mimeType': 'video/VP8', 'payloadType': 101, 'clockRate': 90000, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack', 'parameter': ''}]}], 'headerExtensions': [], 'encodings': [{'ssrc': 375858186, 'scalabilityMode': 'S3T3', 'maxBitrate': 5000000}], 'rtcp': {'cname': 'CDPyD+que2nSyfrN', 'reducedSize': True, 'mux': True}, 'mid': '0'}, 'type': 'simulcast'}
INFO:Signaling:on producer:remove
0:00:00.206824007 290403 0x55defabf6c40 INFO                  python mediasoupbin.py:280:_consume_done: ms _consume_done {'producerId': '164e4ecf-0321-4b4c-b205-922625218f3b', 'local_ip': '127.0.0.1', 'local_rtpPort': 60351, 'local_rtcpPort': 35402, 'transportId': '2799c353-8a01-46e7-98b7-daae1fc9d273', 'ip': '3.7.96.44', 'rtpPort': 45618, 'rtcpPort': 44137, 'sctpParameters': None, 'kind': 'video', 'consumerId': '08e570fd-a1a0-4b77-b4c6-39e4e68ad539', 'encoding_name': 'VP8', 'codec': 'vp8', 'clockRate': 90000, 'pt': 101, 'ssrc': 375858186}
0:00:00.206859464 290403 0x55defabf6c40 DEBUG                 python mediasoupbin.py:283:_consume_done: ms _produce_done desc=
rtpbin name=rtpbin latency=200 rtp-profile=avpf do-retransmission=true

udpsrc name=rtp_udpsrc caps=application/x-rtp,media=video,clock-rate=90000,encoding-name=VP8,payload=101
    ! rtpbin.recv_rtp_sink_0

rtpbin.
    ! rtpvp8depay 
    ! vp8dec name=sink

rtpbin.send_rtcp_src_0 
    ! udpsink name=rtcp_udpsink host=3.7.96.44 port=44137 sync=false async=false 

udpsrc name=rtcp_udpsrc 
    ! rtpbin.recv_rtcp_sink_0 

INFO:MediaSoup:resumeConsumer 2799c353-8a01-46e7-98b7-daae1fc9d273 08e570fd-a1a0-4b77-b4c6-39e4e68ad539
INFO:Signaling:request consumerResume
INFO:Signaling:do_consumerResume {'transportId': '2799c353-8a01-46e7-98b7-daae1fc9d273', 'consumerId': '08e570fd-a1a0-4b77-b4c6-39e4e68ad539'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/resume HTTP/1.1" 400 63
ERROR:MediaSoup:consume resumeConsumer error: 400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://10.0.1.142:4443/rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/resume
0:00:00.216322355 290403 0x55defabf6c40 ERROR                 python mediasoupbin.py:223:_on_error: ms error 400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://10.0.1.142:4443/rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/resume
0:00:00.216593529 290403 0x55defabf6c40 INFO                  python mediasoupbin.py:112:do_request_new_pad: ms do_request_new_pad name_template=audio_src direction=1 name=None caps=None
0:00:00.216708377 290403 0x55defabf6c40 INFO                  python mediasoupbin.py:182:on_pad_linked: audio_src on_pad_linked audio/x-raw, producer-id=(string)65dd535e-8671-4985-809b-09348021a7f7
INFO:MediaSoup:consume {'producerId': '65dd535e-8671-4985-809b-09348021a7f7', 'local_ip': '127.0.0.1', 'local_rtpPort': 47424, 'local_rtcpPort': 50710}
INFO:Signaling:request createPlainRtpTransport
INFO:Signaling:do_createPlainRtpTransport {'type': 'plain', 'comedia': False, 'rtcpMux': False, 'enableSctp': False, 'appData': {}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports HTTP/1.1" 200 92
INFO:MediaSoup:consume createPlainRtpTransport {'id': '7f81e80e-7a59-4fd8-aa12-ba4182dda08a', 'ip': '3.7.96.44', 'port': 49619, 'rtcpPort': 44662}
INFO:Signaling:request plainRtpTransportConnect
INFO:Signaling:do_plainRtpTransportConnect {'transportId': '7f81e80e-7a59-4fd8-aa12-ba4182dda08a', 'ip': '127.0.0.1', 'port': 47424, 'rtcpPort': 50710}
INFO:Signaling:do_transportProduce {'transportId': '7f81e80e-7a59-4fd8-aa12-ba4182dda08a', 'ip': '127.0.0.1', 'port': 47424, 'rtcpPort': 50710}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports/7f81e80e-7a59-4fd8-aa12-ba4182dda08a/connect HTTP/1.1" 200 0
INFO:MediaSoup:consume plainRtpTransportConnect {}
INFO:Signaling:request transportConsume
INFO:Signaling:do_transportConsume {'producerId': '65dd535e-8671-4985-809b-09348021a7f7', 'transportId': '7f81e80e-7a59-4fd8-aa12-ba4182dda08a', 'paused': True, 'rtpCapabilities': {'codecs': [{'mimeType': 'audio/opus', 'clockRate': 48000, 'kind': 'audio', 'preferredPayloadType': 100, 'channels': 2, 'parameters': {'useinbandfec': 1}, 'rtcpFeedback': []}, {'mimeType': 'video/VP8', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 101, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack'}]}, {'mimeType': 'video/VP9', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 103, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack'}]}, {'mimeType': 'video/H264', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 107, 'parameters': {'packetization-mode': 1, 'profile-level-id': '42e01f', 'level-asymmetry-allowed': 1}, 'rtcpFeedback': [{'type': 'nack'}]}, {'mimeType': 'video/H265', 'clockRate': 90000, 'kind': 'video', 'preferredPayloadType': 109, 'parameters': {}, 'rtcpFeedback': [{'type': 'nack'}]}]}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports/7f81e80e-7a59-4fd8-aa12-ba4182dda08a/consume HTTP/1.1" 200 455
INFO:MediaSoup:consume transportConsume {'id': 'a88379db-e133-4c0c-acc9-fa0335659169', 'producerId': '65dd535e-8671-4985-809b-09348021a7f7', 'kind': 'audio', 'rtpParameters': {'codecs': [{'mimeType': 'audio/opus', 'payloadType': 100, 'clockRate': 48000, 'channels': 2, 'parameters': {'minptime': 10, 'useinbandfec': 1, 'sprop-stereo': 1, 'usedtx': 1}, 'rtcpFeedback': []}], 'headerExtensions': [], 'encodings': [{'ssrc': 402024718}], 'rtcp': {'cname': 'CDPyD+que2nSyfrN', 'reducedSize': True, 'mux': True}, 'mid': '0'}, 'type': 'simple'}
INFO:Signaling:on producer:remove
0:00:00.231422615 290403 0x55defabf6c40 INFO                  python mediasoupbin.py:280:_consume_done: ms _consume_done {'producerId': '65dd535e-8671-4985-809b-09348021a7f7', 'local_ip': '127.0.0.1', 'local_rtpPort': 47424, 'local_rtcpPort': 50710, 'transportId': '7f81e80e-7a59-4fd8-aa12-ba4182dda08a', 'ip': '3.7.96.44', 'rtpPort': 49619, 'rtcpPort': 44662, 'sctpParameters': None, 'kind': 'audio', 'consumerId': 'a88379db-e133-4c0c-acc9-fa0335659169', 'encoding_name': 'OPUS', 'codec': 'opus', 'clockRate': 48000, 'pt': 100, 'ssrc': 402024718, 'channels': 2}
0:00:00.231457182 290403 0x55defabf6c40 DEBUG                 python mediasoupbin.py:283:_consume_done: ms _produce_done desc=
rtpbin name=rtpbin latency=200 rtp-profile=avpf do-retransmission=true

udpsrc name=rtp_udpsrc caps=application/x-rtp,media=audio,clock-rate=48000,encoding-name=OPUS,payload=100
    ! rtpbin.recv_rtp_sink_0

rtpbin.
    ! rtpopusdepay 
    ! opusdec name=sink

rtpbin.send_rtcp_src_0 
    ! udpsink name=rtcp_udpsink host=3.7.96.44 port=44662 sync=false async=false 

udpsrc name=rtcp_udpsrc 
    ! rtpbin.recv_rtcp_sink_0 

INFO:MediaSoup:resumeConsumer 7f81e80e-7a59-4fd8-aa12-ba4182dda08a a88379db-e133-4c0c-acc9-fa0335659169
INFO:Signaling:request consumerResume
INFO:Signaling:do_consumerResume {'transportId': '7f81e80e-7a59-4fd8-aa12-ba4182dda08a', 'consumerId': 'a88379db-e133-4c0c-acc9-fa0335659169'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "POST /rooms/test/broadcasters/b47381080/transports/7f81e80e-7a59-4fd8-aa12-ba4182dda08a/resume HTTP/1.1" 400 63
ERROR:MediaSoup:consume resumeConsumer error: 400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://10.0.1.142:4443/rooms/test/broadcasters/b47381080/transports/7f81e80e-7a59-4fd8-aa12-ba4182dda08a/resume
0:00:00.237867305 290403 0x55defabf6c40 ERROR                 python mediasoupbin.py:223:_on_error: ms error 400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://10.0.1.142:4443/rooms/test/broadcasters/b47381080/transports/7f81e80e-7a59-4fd8-aa12-ba4182dda08a/resume
Setting pipeline to PAUSED ...
0:00:00.241988901 290403 0x55defabf6c40 ERROR             jackclient gstjackaudioclient.c:35:jack_log_error: Cannot connect to server socket err = No such file or directory
0:00:00.242005908 290403 0x55defabf6c40 ERROR             jackclient gstjackaudioclient.c:35:jack_log_error: Cannot connect to server request channel
0:00:00.244072474 290403 0x55defabf6c40 ERROR             jackclient gstjackaudioclient.c:35:jack_log_error: jack server is not running or cannot be started
0:00:00.244180817 290403 0x55defabf6c40 ERROR             jackclient gstjackaudioclient.c:35:jack_log_error: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
0:00:00.244194054 290403 0x55defabf6c40 ERROR             jackclient gstjackaudioclient.c:35:jack_log_error: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
0:00:00.244203087 290403 0x55defabf6c40 WARN              jackclient gstjackaudioclient.c:381:gst_jack_audio_get_connection: could not create connection
0:00:00.244243602 290403 0x55defabf6c40 WARN                jacksink gstjackaudiosink.c:355:gst_jack_ring_buffer_open_device:<autoaudiosink0-actual-sink-jackaudio> error: Jack server not found
0:00:00.244252073 290403 0x55defabf6c40 WARN                jacksink gstjackaudiosink.c:355:gst_jack_ring_buffer_open_device:<autoaudiosink0-actual-sink-jackaudio> error: Cannot connect to the Jack server (status 17)
0:00:00.244619046 290403 0x55defabf6c40 WARN                 default oss4-property-probe.c:302:gst_oss4_property_probe_get_values:<autoaudiosink0-actual-sink-oss4> Can't open file descriptor to probe available devices: No such file or directory
0:00:00.244638710 290403 0x55defabf6c40 WARN                oss4sink oss4-sink.c:513:gst_oss4_sink_open:<autoaudiosink0-actual-sink-oss4> error: Could not open audio device for playback.
0:00:00.244648797 290403 0x55defabf6c40 WARN                oss4sink oss4-sink.c:513:gst_oss4_sink_open:<autoaudiosink0-actual-sink-oss4> error: system error: No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
0:00:00.251740570 290403 0x55defabf6c40 WARN                  openal gstopenalsink.c:634:gst_openal_sink_open:<autoaudiosink0-actual-sink-openal> error: Could not open device.
0:00:00.251753309 290403 0x55defabf6c40 WARN                  openal gstopenalsink.c:634:gst_openal_sink_open:<autoaudiosink0-actual-sink-openal> error: ALC error: Out of Memory
0:00:00.251983284 290403 0x55defabf6c40 WARN                     oss gstosssink.c:398:gst_oss_sink_open:<autoaudiosink0-actual-sink-oss> error: Could not open audio device for playback.
0:00:00.251996921 290403 0x55defabf6c40 WARN                     oss gstosssink.c:398:gst_oss_sink_open:<autoaudiosink0-actual-sink-oss> error: system error: No such file or directory
error: XDG_RUNTIME_DIR not set in the environment.
0:00:00.267677918 290403 0x55defabf6c40 WARN                gleglgbm gstgl_gbm_utils.c:473:gst_gl_gbm_find_and_open_drm_node: Found no matching DRM devices
0:00:00.267699226 290403 0x55defabf6c40 ERROR              gldisplay gstgldisplay_gbm.c:439:gst_gl_display_gbm_new: could not find or open DRM device
0:00:00.268319705 290403 0x55defabf6c40 WARN                glwindow gstglwindow.c:288:gst_gl_window_new: Could not create window. user specified (null), creating dummy window
0:00:00.268441486 290403 0x55defac6f920 WARN               glcontext gstglcontext.c:1240:gst_gl_context_create_thread:<glcontextegl0> Failed to create context
0:00:00.268486889 290403 0x55defabf6c40 WARN             glimagesink gstglimagesink.c:1010:_ensure_gl_setup:<sink> error: Failed to initialize egl: EGL_NOT_INITIALIZED
0:00:01.244526557 290403 0x55defabf6c40 WARN                 kmssink gstkmssink.c:835:gst_kms_sink_start:<autovideosink0-actual-sink-kms> error: Could not open DRM module (NULL)
0:00:01.244550919 290403 0x55defabf6c40 WARN                 kmssink gstkmssink.c:835:gst_kms_sink_start:<autovideosink0-actual-sink-kms> error: reason: No such file or directory (2)
0:00:01.244588588 290403 0x55defabf6c40 WARN                basesink gstbasesink.c:5367:gst_base_sink_change_state:<autovideosink0-actual-sink-kms> error: Failed to start
0:00:01.245101049 290403 0x55defabf6c40 WARN              ximagesink ximagesink.c:859:gst_x_image_sink_xcontext_get:<autovideosink0-actual-sink-ximage> error: Could not initialise X output
0:00:01.245116253 290403 0x55defabf6c40 WARN              ximagesink ximagesink.c:859:gst_x_image_sink_xcontext_get:<autovideosink0-actual-sink-ximage> error: Could not open display
error: XDG_RUNTIME_DIR not set in the environment.
0:00:01.245544582 290403 0x55defabf6c40 WARN             waylandsink gstwaylandsink.c:359:gst_wayland_sink_find_display:<autovideosink0-actual-sink-wayland> warning: Could not initialise Wayland output
0:00:01.245556742 290403 0x55defabf6c40 WARN             waylandsink gstwaylandsink.c:359:gst_wayland_sink_find_display:<autovideosink0-actual-sink-wayland> warning: Failed to create GstWlDisplay: 'Failed to connect to the wayland display '(default)''
0:00:01.246324990 290403 0x55defabf6c40 DEBUG                 python mediasoupbin.py:208:do_state_changed: ms do_state_changed oldstate=<enum GST_STATE_NULL of type Gst.State> newstate=<enum GST_STATE_READY of type Gst.State> pending=<enum GST_STATE_VOID_PENDING of type Gst.State>
0:00:01.246668882 290403 0x55defabf6c40 DEBUG                 python mediasoupbin.py:208:do_state_changed: ms do_state_changed oldstate=<enum GST_STATE_READY of type Gst.State> newstate=<enum GST_STATE_PAUSED of type Gst.State> pending=<enum GST_STATE_VOID_PENDING of type Gst.State>
Pipeline is live and does not need PREROLL ...
ERROR: from element /GstPipeline:pipeline0/mediasoupbin+MediaSoupBin:ms: 400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://10.0.1.142:4443/rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/resume
Additional debug info:
400 Client Error: req.room.resumeBroadcasterConsumer is not a function for url: https://10.0.1.142:4443/rooms/test/broadcasters/b47381080/transports/2799c353-8a01-46e7-98b7-daae1fc9d273/resume
ERROR: pipeline doesn't want to preroll.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
0:00:01.247653671 290403 0x55defabf6c40 DEBUG                 python mediasoupbin.py:208:do_state_changed: ms do_state_changed oldstate=<enum GST_STATE_PAUSED of type Gst.State> newstate=<enum GST_STATE_READY of type Gst.State> pending=<enum GST_STATE_VOID_PENDING of type Gst.State>
Setting pipeline to NULL ...
0:00:01.247920515 290403 0x55defabf6c40 DEBUG                 python mediasoupbin.py:208:do_state_changed: ms do_state_changed oldstate=<enum GST_STATE_READY of type Gst.State> newstate=<enum GST_STATE_NULL of type Gst.State> pending=<enum GST_STATE_VOID_PENDING of type Gst.State>
INFO:MediaSoup:stop
INFO:Signaling:stop
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.0.1.142:4443
DEBUG:urllib3.connectionpool:https://10.0.1.142:4443 "DELETE /rooms/test/broadcasters/b47381080 HTTP/1.1" 200 19
Freeing pipeline ...
root@ip-10-0-1-142:/home/ubuntu/vpalmisano/mediasoupbin#

**Comment by vpalmisano** [comment]
MIssing something on server code, you need to add a `resumeBroadcasterConsumer` in the server/Room.js code.
